---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/authors/{author_id}/articles/{article_id}/unpublished":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    get:
      summary: unpublished article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/articles/{article_id}/published":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    get:
      summary: published article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/articles/{article_id}/last_ten_comments":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    get:
      summary: last_ten_comments article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/articles/{article_id}/search_current_value":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    post:
      summary: search_current_value article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/articles/{article_id}/filtration_articles":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    post:
      summary: filtration_articles article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/articles/{article_id}/sorting_articles":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    post:
      summary: sorting_articles article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/articles":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    get:
      summary: list articles
      responses:
        '200':
          description: successful
    post:
      summary: create article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/articles/{id}":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      responses:
        '200':
          description: successful
    patch:
      summary: update article
      responses:
        '200':
          description: successful
    put:
      summary: update article
      responses:
        '200':
          description: successful
    delete:
      summary: delete article
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
